server:
  port: 8081
spring:
  application:
    name: customer
  datasource:
    password: password
    url: jdbc:postgresql://0.0.0.0:5433/customer
    username: amigoscode
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/